### ISSUE TITLE
Permission denied when running ggt node run nodeV1

### ISSUE THREAD

**Issue by gatesyp** [multisig-labs/GoGoTools#1]
I downloaded a fresh version of the avalanchego binary from the [Ava release page](https://github.com/ava-labs/avalanchego/releases/tag/v1.9.7), and can run it directly via `./avalanchego`

When running it through `ggt node run nodeV1`, getting this permissions error: 

<img width="1115" alt="CleanShot 2023-01-25 at 13 18 02@2x" src="https://user-images.githubusercontent.com/13278417/214550052-40b2cef5-77b5-4fae-9ebd-5355b82b8e2b.png">

```Error: fork/exec nodeV1/bin/avalanchego: permission denied```

Side note, surprised that there is an avalanchego binary in the `nodeV1/bin directory` -- does ggt copy the binary I passed in into this directory? 

Similarly for the `subnet-evm` instance -- there is already something in the plugins folder

**Comment by gatesyp** [comment]
i deleted the existing `avalanchego` binary and moved my downloaded binary into the `nodeV1/bin` directory, reran `ggt node run nodeV1`, and getting this error now: 
<img width="592" alt="CleanShot 2023-01-25 at 13 29 22@2x" src="https://user-images.githubusercontent.com/13278417/214552258-49bc7a4d-0a48-4185-ad0a-63df582bed8e.png">

**Comment by 0xJohnnyGault** [comment]
try using a full path, don't use ~

We symlink the binaries into the dir, so that each dir can be an isolated env with diff versions of avago and vm

**Comment by 0xJohnnyGault** [comment]
also use the exact full path and filename not just the path to the bins

**Comment by gatesyp** [comment]
^ using exact full path with filename worked
