### ISSUE TITLE
Verbose flag doesnt work

### ISSUE THREAD

**Issue by gatesyp** [multisig-labs/GoGoTools#2]
I already have a NodeV1 running (but didn't realize it), and in another Terminal I ran `ggt run nodeV1`. It ended with no error message and prompted to use the --verbose flag, which doesn't do anything: 

<img width="671" alt="CleanShot 2023-01-26 at 12 47 07@2x" src="https://user-images.githubusercontent.com/13278417/214817419-f8343010-02bb-4e01-b57d-733aad36e912.png">

kind of a nit, but thought I'd make an issue for awareness

**Comment by 0xJohnnyGault** [comment]
Yes this part fo the app needs a lot of love.
