### ISSUE TITLE
resource temporarily unavailable when trying to create first chain

### ISSUE THREAD

**Issue by gatesyp** [multisig-labs/GoGoTools#3]
From docs: 

```
In another terminal, lets create our subnet (the ggt utils init cmd creates a sample genesis with all precompiles enabled):

ggt wallet create-chain MyChain subnetevm genesis.json
```

When running the command, I get this output: 

<img width="1043" alt="CleanShot 2023-01-26 at 12 51 04@2x" src="https://user-images.githubusercontent.com/13278417/214818094-8845f62c-6ce5-42b4-98e7-ff94233b107a.png">

I checked the log, and has the error: 
```
[01-26|12:47:02.821] FATAL process/process.go:130 error initializing node {"error": "problem initializing database: couldn't create db at nodeV1/data/db/local/v1.4.5: resource temporarily unavailable"}
```

Also, would be nice to return a "hello world" -ish RPC command? so user can quickly see that the subnet is live (or not)

eg 
```
curl -X POST --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":67}' http://localhost:9650/ext/bc/Kc3vF4GVF8Wm2gcRiqau7weZRcPbstB5kWN9LrKa7Lop9cZCw/rpc
```

^^ this returns 404 not found for me btw, assumedly because of the error

(rpc method from [eth docs](https://ethereum.org/en/developers/docs/apis/json-rpc/#net_version))

**Comment by 0xJohnnyGault** [comment]
If this happens its because another node is running. 

`killall avalanchego`
