### ISSUE TITLE
parse error when running ggt node info | jq

### ISSUE THREAD

**Issue by gatesyp** [multisig-labs/GoGoTools#4]
following the docs, getting the error: 

``` 
parse error: Expected value before ',' at line 1, column 1774
```
when running `ggt node info | jq`. 

I have jq installed -- worth noting that when I ran this, the subnet creation failed (related to #3  )

**Comment by 0xJohnnyGault** [comment]
If this happens, try running the command with the `| jq` pipe to see what the underlying problem is.
